# Generated by Django 4.1 on 2023-09-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_location_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(max_length=20, verbose_name='Название улицы'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', models.F('end_date'))), name='start_before_end'),
        ),
    ]
