# Generated by Django 4.2.5 on 2023-09-19 11:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0002_alter_order_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="time",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (8, "08:00"),
                    (9, "09:00"),
                    (10, "10:00"),
                    (11, "11:00"),
                    (12, "12:00"),
                    (13, "13:00"),
                    (14, "14:00"),
                    (15, "15:00"),
                    (16, "16:00"),
                    (17, "17:00"),
                    (18, "18:00"),
                    (19, "19:00"),
                ],
                max_length=9,
            ),
        ),
    ]
