# Generated by Django 4.2.5 on 2023-10-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название Мероприятия')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('meeting_quantity', models.PositiveSmallIntegerField(verbose_name='Количество мест')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=128, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос - ответ',
                'verbose_name_plural': 'Выпросы и ответы',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Правило')),
                ('text', models.TextField(verbose_name='Текст правила')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
            },
        ),
    ]
