# Generated by Django 4.2.5 on 2023-09-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудования'},
        ),
        migrations.AlterModelOptions(
            name='spot',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.RemoveField(
            model_name='price',
            name='spot',
        ),
    ]
