# Generated by Django 4.2.5 on 2023-10-07 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_event_question_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraphoto',
            name='description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='plan_photo',
        ),
        migrations.AddField(
            model_name='location',
            name='days_open',
            field=models.CharField(choices=[('пн-вс', 'пн-вс'), ('пн-сб', 'пн-сб'), ('пн-пт', 'пн-пт')], default=('пн-вс', 'пн-вс'), max_length=32, verbose_name='Дни недели через -'),
        ),
        migrations.AddField(
            model_name='location',
            name='short_annotation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткая аннотация'),
        ),
        migrations.CreateModel(
            name='PlanPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/plans/', verbose_name='Фото-план')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_photo', to='spots.location')),
            ],
            options={
                'verbose_name': 'Фото-план',
                'verbose_name_plural': 'Фото-планы',
                'ordering': ('location',),
            },
        ),
    ]
