# Generated by Django 4.2.5 on 2023-09-18 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0003_alter_location_street_order_start_before_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="street",
            field=models.TextField(verbose_name="Название улицы"),
        ),
        migrations.AlterField(
            model_name="order",
            name="bill",
            field=models.IntegerField(verbose_name="итоговый счет"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("Booked", "Booked"), ("Lock", "Lock")],
                default="Booked",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="raiting",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="Оценка отзыва",
            ),
        ),
        migrations.AlterField(
            model_name="spot",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Название коворкинга"),
        ),
    ]
