# Generated by Django 4.2.5 on 2023-10-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_event_question_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='days_open',
            field=models.CharField(choices=[('пн-вс', 'пн-вс'), ('пн-сб', 'пн-сб'), ('пн-пт', 'пн-пт')], default=('пн-вс', 'пн-вс'), max_length=5, verbose_name='Дни недели через -'),
        ),
        migrations.AddField(
            model_name='location',
            name='short_annotation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткая аннотация'),
        ),
    ]
