# Generated by Django 4.2.5 on 2023-10-10 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_remove_extraphoto_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='icon',
            field=models.FileField(default=1, upload_to='icons/equipment/', validators=[django.core.validators.FileExtensionValidator('svg')]),
            preserve_default=False,
        ),
    ]
