# Generated by Django 4.2.5 on 2023-09-19 15:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0004_alter_order_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={"verbose_name": "Избранное", "verbose_name_plural": "Избранное"},
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="pub_date",
        ),
        migrations.AlterField(
            model_name="order",
            name="time",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("08:00", "08:00 -09:00"),
                    ("09:00", "09:00 -10:00"),
                    ("10:00", "10:00 -11:00"),
                    ("11:00", "11:00 -12:00"),
                    ("12:00", "12:00 -13:00"),
                    ("13:00", "13:00 -14:00"),
                    ("14:00", "14:00 -15:00"),
                    ("15:00", "15:00 -16:00"),
                    ("16:00", "16:00 -17:00"),
                    ("17:00", "17:00 -18:00"),
                    ("18:00", "18:00 -19:00"),
                    ("19:00", "19:00 -20:00"),
                ],
                max_length=12,
            ),
        ),
    ]
