# Generated by Django 4.2.5 on 2023-10-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_remove_extraphoto_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='plan_photo',
        ),
    ]
