# Generated by Django 4.2.5 on 2023-10-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0006_remove_equipment_description_question_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
