# Generated by Django 4.2.5 on 2023-10-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0006_remove_location_plan_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/plans/', verbose_name='Фото-план')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_photo', to='spots.location')),
            ],
            options={
                'verbose_name': 'Фото-план',
                'verbose_name_plural': 'Фото-планы',
                'ordering': ('location',),
            },
        ),
    ]
