# Generated by Django 4.2.5 on 2023-10-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0007_alter_review_description_alter_spot_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallMainPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/small_main_photo/', verbose_name='Укороченное фото')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='small_main_photo', to='spots.location')),
            ],
            options={
                'verbose_name': 'Укороченное фото',
                'verbose_name_plural': 'Укороченные фото',
                'ordering': ('location',),
            },
        ),
    ]
