# Generated by Django 4.2.5 on 2023-10-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0007_alter_review_description_alter_spot_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Главное укороченное фото локации', upload_to='images/main_small_photo/', verbose_name='Главное укороченное фото ')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='small_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spots.smallimage'),
        ),
    ]
