# Generated by Django 4.2.5 on 2023-10-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0008_smallmainphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
