# Generated by Django 4.2.5 on 2023-10-15 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0009_delete_event_delete_question_delete_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="close_time",
            field=models.TimeField(
                choices=[
                    (datetime.time(1, 0), "00:55"),
                    (datetime.time(2, 0), "01:55"),
                    (datetime.time(3, 0), "02:55"),
                    (datetime.time(4, 0), "03:55"),
                    (datetime.time(5, 0), "04:55"),
                    (datetime.time(6, 0), "05:55"),
                    (datetime.time(7, 0), "06:55"),
                    (datetime.time(8, 0), "07:55"),
                    (datetime.time(9, 0), "08:55"),
                    (datetime.time(10, 0), "09:55"),
                    (datetime.time(11, 0), "10:55"),
                    (datetime.time(12, 0), "11:55"),
                    (datetime.time(13, 0), "12:55"),
                    (datetime.time(14, 0), "13:55"),
                    (datetime.time(15, 0), "14:55"),
                    (datetime.time(16, 0), "15:55"),
                    (datetime.time(17, 0), "16:55"),
                    (datetime.time(18, 0), "17:55"),
                    (datetime.time(19, 0), "18:55"),
                    (datetime.time(20, 0), "19:55"),
                    (datetime.time(21, 0), "20:55"),
                    (datetime.time(22, 0), "21:55"),
                    (datetime.time(23, 0), "22:55"),
                    (datetime.time(0, 0), "23:55"),
                ],
                default=datetime.time(1, 0),
                verbose_name="Время закрытия",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="open_time",
            field=models.TimeField(
                choices=[
                    (datetime.time(0, 0), "00:00"),
                    (datetime.time(1, 0), "01:00"),
                    (datetime.time(2, 0), "02:00"),
                    (datetime.time(3, 0), "03:00"),
                    (datetime.time(4, 0), "04:00"),
                    (datetime.time(5, 0), "05:00"),
                    (datetime.time(6, 0), "06:00"),
                    (datetime.time(7, 0), "07:00"),
                    (datetime.time(8, 0), "08:00"),
                    (datetime.time(9, 0), "09:00"),
                    (datetime.time(10, 0), "10:00"),
                    (datetime.time(11, 0), "11:00"),
                    (datetime.time(12, 0), "12:00"),
                    (datetime.time(13, 0), "13:00"),
                    (datetime.time(14, 0), "14:00"),
                    (datetime.time(15, 0), "15:00"),
                    (datetime.time(16, 0), "16:00"),
                    (datetime.time(17, 0), "17:00"),
                    (datetime.time(18, 0), "18:00"),
                    (datetime.time(19, 0), "19:00"),
                    (datetime.time(20, 0), "20:00"),
                    (datetime.time(21, 0), "21:00"),
                    (datetime.time(22, 0), "22:00"),
                    (datetime.time(23, 0), "23:00"),
                ],
                default=datetime.time(0, 0),
                verbose_name="Время открытия",
            ),
        ),
    ]
