# Generated by Django 4.2.5 on 2023-10-20 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0010_alter_location_close_time_alter_location_open_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_user_order_review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='booked_spot',
            field=models.OneToOneField(error_messages={'unique': 'Отзыв у этого Заказа уже существует.'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='spots.order', verbose_name='Заказ'),
        ),
    ]
