# Generated by Django 4.2.5 on 2023-10-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0011_remove_review_unique_user_order_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
