# Generated by Django 4.2.5 on 2023-10-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0012_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='days_open',
            field=models.CharField(choices=[('Пн-Вс', 'Пн-Вс'), ('Пн-Сб', 'Пн-Сб'), ('Пн-Пт', 'Пн-Пт')], default=('Пн-Вс', 'Пн-Вс'), max_length=32, verbose_name='Дни недели через -'),
        ),
    ]
