# Generated by Django 4.2.5 on 2023-10-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0013_alter_location_days_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date', 'start_time'), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
