# Generated by Django 4.2.5 on 2023-10-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Род деятельности'),
        ),
    ]
