# Generated by Django 4.1 on 2023-09-14 13:12

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=32, validators=[users.validators.TelegramUsernameValidator], verbose_name='telegram'),
        ),
    ]
