# Generated by Django 4.2.5 on 2023-10-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Этот адрес электронной почты уже зарегистрован.'}, max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
