# Generated by Django 4.2.5 on 2023-10-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='have_orders',
            field=models.BooleanField(default=False, verbose_name='Имеет заказы'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан на рассылку'),
        ),
    ]
