# Generated by Django 4.2.5 on 2023-10-27 07:26

from django.db import migrations, models
import users.service


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.service.get_avatar_path, verbose_name='Аватар'),
        ),
    ]
