# Generated by Django 4.2.5 on 2023-10-31 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_have_orders_user_is_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='have_orders',
        ),
    ]
