# Generated by Django 4.2.5 on 2023-11-20 17:50

from django.db import migrations
import users.fields
import users.service


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_have_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=users.fields.CompressedImageField(
                blank=True, null=True, quality=70, upload_to=users.service.get_avatar_path, verbose_name='Аватар'),
        ),
    ]
