# Generated by Django 4.2.5 on 2023-10-25 09:19

from django.db import migrations, models
import django.db.models.deletion
import promo.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название промокода')),
                ('percent_discount', models.PositiveSmallIntegerField(validators=[promo.validators.MaxDiscountValidator(50)], verbose_name='Процент скидки')),
                ('expiry_date', models.DateField(validators=[promo.validators.validate_datetime_less_present], verbose_name='Дата истечения')),
                ('balance', models.PositiveIntegerField(verbose_name='Количество использований')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ('expiry_date',),
            },
        ),
        migrations.CreateModel(
            name='EmailNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_message', models.CharField(max_length=128, verbose_name='Тема письма')),
                ('text_message', models.TextField(verbose_name='Текст письма')),
                ('send_datetime', models.DateTimeField(unique=True, validators=[promo.validators.validate_datetime_less_present], verbose_name='Дата и время отправки')),
                ('promo_code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocode', to='promo.promocode')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ('send_datetime',),
            },
        ),
    ]
