# Generated by Django 4.2.5 on 2023-10-28 01:14

from django.db import migrations, models
import django.db.models.deletion
import promo.validators


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnews',
            options={'ordering': ('send_datetime',), 'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.RemoveField(
            model_name='emailnews',
            name='send_date',
        ),
        migrations.AddField(
            model_name='emailnews',
            name='send_datetime',
            field=models.DateTimeField(blank=True, null=True, unique=True, validators=[promo.validators.validate_datetime_less_present], verbose_name='Дата и время отправки'),
        ),
        migrations.AddField(
            model_name='emailnews',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
