# Generated by Django 4.2.5 on 2023-10-28 01:15

from django.db import migrations, models
import django.utils.timezone
import promo.validators


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_alter_emailnews_options_remove_emailnews_send_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnews',
            name='send_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True, validators=[promo.validators.validate_datetime_less_present], verbose_name='Дата и время отправки'),
            preserve_default=False,
        ),
    ]
