# Generated by Django 4.2.5 on 2023-10-29 12:31

from django.db import migrations, models
import promo.validators


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_alter_emailnews_send_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry_date',
            field=models.DateField(validators=[promo.validators.validate_date_less_present], verbose_name='Дата истечения'),
        ),
    ]
