version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    
  
  redis:
    image: redis:latest
    restart: always
  
  minio:
    image: minio/minio:latest
    volumes:
      - minio_value:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../.env
    command: server /data --console-address :9001

  backend:
    build:
      context: ../api_spot
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    env_file:
      - ../.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      # - "9000:9000"
      # - "9001:9001"
    volumes:
      - ./nginx/minio.conf:/etc/nginx/conf.d/default.conf
      # - minio_value:/var/html/static/
      # - static_value:/var/html/static/
      # - media_value:/var/html/media/
    links:
      - backend
    depends_on:
      - backend
      # - frontend


  
volumes:
  # static_value:
  # media_value:
  postgres_data:
  minio_value:
