# Generated by Django 4.2.5 on 2023-10-14 14:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="text",
            field=ckeditor.fields.RichTextField(verbose_name="Текст правила"),
        ),
    ]
