# Generated by Django 4.2.5 on 2023-10-14 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0002_alter_rule_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="icon",
        ),
        migrations.AddField(
            model_name="rule",
            name="icon",
            field=models.FileField(
                default=1,
                upload_to="icons/rules/",
                validators=[django.core.validators.FileExtensionValidator(("svg",))],
            ),
            preserve_default=False,
        ),
    ]
